// Generated by scripts/build_courses.py from data/ws26_27_courses.js.
// Do not edit by hand. Missing official values stay null.
import type { Course } from "../types";

export const courses: Course[] = [
  {
    "id": "3muecl011v-ws26-27",
    "code": "3MUECL011V",
    "semesterId": "WS26-27",
    "area": "Basics of HCI",
    "modules": [
      {
        "code": "3HCIMA001",
        "name": "Humans & Technology"
      }
    ],
    "name": "Analysis & Evaluation",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1
    ],
    "offeringFrequency": "Winter semester only",
    "ects": 4.5,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "US-C 116",
    "lecturers": [
      "Dipl.-Wirt.-Inform. Sven Bittenbinder",
      "Sourav Bhattacharjee",
      "Univ.-Prof. Dr. Claudia Müller"
    ]
  },
  {
    "id": "3sadeg001v-ws26-27",
    "code": "3SADEG001V",
    "semesterId": "WS26-27",
    "area": "Basics of HCI",
    "modules": [
      {
        "code": "3HCIMA001",
        "name": "Humans & Technology"
      }
    ],
    "name": "Human-Computer Interaction",
    "requirementStatus": null,
    "recommendedSemesters": [
      1
    ],
    "offeringFrequency": "Every 2nd semester",
    "ects": 4.5,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": "US-C 114",
    "lecturers": [
      "Jun.-Prof. Dr.-Ing. Shadan Sadeghian Borojeni"
    ],
    "lectureGroupFrequency": "Every semester"
  },
  {
    "id": "43uco1111v-ws26-27",
    "code": "43UCO1111V",
    "semesterId": "WS26-27",
    "area": "Consolidation",
    "modules": [
      {
        "code": "3HCIMA018",
        "name": "Ubiquitous Computing & Usable Security"
      }
    ],
    "name": "Ubiquitous Computing",
    "requirementStatus": null,
    "recommendedSemesters": [
      2
    ],
    "offeringFrequency": "Every semester",
    "ects": 4.5,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "H-C 8326",
    "lecturers": [
      "Univ.-Prof. Dr. Kristof Van Laerhoven"
    ]
  },
  {
    "id": "3steve014v-ws26-27",
    "code": "3STEVE014V",
    "semesterId": "WS26-27",
    "area": "Consolidation",
    "modules": [
      {
        "code": "3HCIMA018",
        "name": "Ubiquitous Computing & Usable Security"
      }
    ],
    "name": "Usable Security",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      2
    ],
    "offeringFrequency": "Every semester",
    "ects": 4.5,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "US-F 103",
    "lecturers": [
      "Dr. Jenny Darlene Hindrichs"
    ]
  },
  {
    "id": "3wulf0027v-ws26-27",
    "code": "3WULF0027V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Applied Artifical Intelligence for Telecommunication",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      2,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "three weeks turn",
        "dateLabel": "10/14/26 – 1/27/27",
        "startDate": "2026-10-14",
        "endDate": "2027-01-27",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Hon.-Prof. Dr. Roman Englert"
    ],
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "3wulf0022v-ws26-27",
    "code": "3WULF0022V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Integration of Organization and Technology Development - Practical Seminar",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "fortnightly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "US-F 103",
    "lecturers": [
      "Sven Christopher Hoffmann"
    ],
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "3wulf0021v-ws26-27",
    "code": "3WULF0021V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Integration of Organization and Technology Development - Theory Seminar",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "US-A 134/1",
    "lecturers": [
      "apl. Prof. Dr. Markus Rohde"
    ],
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "3pipek016v-ws26-27",
    "code": "3PIPEK016V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Introduction to 3D Printing for Rapid Prototyping",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": null,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Marios Mouratidis M.Sc."
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true,
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "3wulf030v-ws26-27",
    "code": "3WULF030V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Introduction to Sociology - reading seminar",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": null,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/16/26 – 2/5/27",
        "startDate": "2026-10-16",
        "endDate": "2027-02-05",
        "note": null
      }
    ],
    "location": "US-D 109",
    "lecturers": [
      "Leonie Antonia Jahn"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true,
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "3sadeg101v-ws26-27",
    "code": "3SADEG101V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Seminar on Interaction with Automation (SIA)",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": null,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true,
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "3muecl005v-ws26-27",
    "code": "3MUECL005V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Participatory and Creative Methods for the Application Field Smart Living",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": null,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "US-D 321",
    "lecturers": [
      "Sourav Bhattacharjee",
      "Univ.-Prof. Dr. Claudia Müller"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true,
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "3wulf0024v-ws26-27",
    "code": "3WULF0024V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Robotik im realweltlichen Einsatz im Bereich der sozialen Arbeit",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": "Every 2nd semester",
    "ects": null,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "US-D 109",
    "lecturers": [
      "Dr. Rainer Wieching"
    ],
    "lectureGroupFrequency": "Every semester",
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "3wulf0012v-ws26-27",
    "code": "3WULF0012V",
    "semesterId": "WS26-27",
    "area": "Current Research",
    "modules": [
      {
        "code": "3HCIMA008",
        "name": "Current Research in HCI I"
      },
      {
        "code": "3HCIMA009",
        "name": "Current Research in HCI II"
      },
      {
        "code": "3HCIMA010",
        "name": "Current Research in HCI III"
      },
      {
        "code": "3HCIMA021",
        "name": "Current Research in HCI IV"
      }
    ],
    "name": "Spezielle Aspekte der Sozio-Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": "Every 2nd semester",
    "ects": null,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "fortnightly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "US-D 207",
    "lecturers": [
      "apl. Prof. Dr. Markus Rohde"
    ],
    "lectureGroupFrequency": "Every semester",
    "moduleCreditNote": "Each selected seminar counts as 6 ECTS. The seminar exam is 3 ECTS of that module."
  },
  {
    "id": "1sowi1406v-ws26-27",
    "code": "1SOWI1406V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA08",
        "name": "Science, Technology and Media Studies"
      }
    ],
    "name": "Agency und Technologie: Technologie in the age of AI",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "H-C 7325",
    "lecturers": [
      "Dr. Jennifer Bosen"
    ],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "science-technology-media",
      "label": "Science, Technology and Media Studies",
      "ects": 3
    }
  },
  {
    "id": "999k25005v-ws26-27",
    "code": "999K25005V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      },
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "Language Center: Change Communication",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": 3,
    "schedule": [
      {
        "day": null,
        "startTime": "08:30",
        "endTime": "17:00",
        "cadence": "block",
        "dateLabel": "3/15/27 – 3/17/27",
        "startDate": "2027-03-15",
        "endDate": "2027-03-17",
        "note": null
      }
    ],
    "location": "F-S 012",
    "lecturers": [],
    "datedGrid": true
  },
  {
    "id": "999f00167v-ws26-27",
    "code": "999F00167V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      },
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      },
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "Language Center: English - Target Level C1.2",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 3,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "single",
        "dateLabel": "12/18/26",
        "startDate": "2026-12-18",
        "endDate": "2026-12-18",
        "note": null
      },
      {
        "day": "Thursday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "single",
        "dateLabel": "12/17/26",
        "startDate": "2026-12-17",
        "endDate": "2026-12-17",
        "note": null
      },
      {
        "day": "Wednesday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "F-S 011",
    "lecturers": []
  },
  {
    "id": "1mewi3828v-ws26-27",
    "code": "1MEWI3828V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA03",
        "name": "Media History and Media Historiography"
      }
    ],
    "name": "Datengeschichte(n)",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "AH-A 013/016",
    "lecturers": [
      "Univ.-Prof. Dr. Daniela Wentz"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "media-history",
      "label": "Media History and Media Historiography",
      "ects": 3
    }
  },
  {
    "id": "3pesch101v-ws26-27",
    "code": "3PESCH101V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3WIMA002",
        "name": "Decision Support"
      }
    ],
    "name": "Decision Support Systems",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every 2nd semester",
    "ects": null,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      },
      {
        "day": "Monday",
        "startTime": "18:00",
        "endTime": "20:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": "US-F 304",
    "lecturers": [
      "Univ.-Prof. Dr. Erwin Pesch"
    ],
    "lectureGroupFrequency": "Every semester",
    "moduleCreditNote": "Decision Support is 9 ECTS. All courses in the module have to be completed before the credits count."
  },
  {
    "id": "43vsa0131v-ws26-27",
    "code": "43VSA0131V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      }
    ],
    "name": "Deep Learning",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "H-C 8326",
    "lecturers": [
      "Univ.-Prof. Dr. rer. nat. Michael Möller"
    ],
    "creditGroup": {
      "id": "deep-learning",
      "label": "Deep Learning",
      "ects": 6,
      "parts": 2
    }
  },
  {
    "id": "43vsa0132v-ws26-27",
    "code": "43VSA0132V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      }
    ],
    "name": "Deep Learning",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "H-C 8326",
    "lecturers": [
      "Jan Philipp Schneider M.Sc."
    ],
    "creditGroup": {
      "id": "deep-learning",
      "label": "Deep Learning",
      "ects": 6,
      "parts": 2
    }
  },
  {
    "id": "43ems0030v-ws26-27",
    "code": "43EMS0030V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Embedded Control",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "H-C 6321",
    "lecturers": [
      "Lehrende des Faches"
    ],
    "creditGroup": {
      "id": "embedded-control",
      "label": "Embedded Control",
      "ects": 9,
      "parts": 2
    }
  },
  {
    "id": "43ems0031v-ws26-27",
    "code": "43EMS0031V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Embedded Control",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "H-C 6321",
    "lecturers": [
      "Utkarsh Raj M.Sc."
    ],
    "creditGroup": {
      "id": "embedded-control",
      "label": "Embedded Control",
      "ects": 9,
      "parts": 2
    }
  },
  {
    "id": "1sowi1404v-ws26-27",
    "code": "1SOWI1404V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA04",
        "name": "Cultural Sociology"
      }
    ],
    "name": "Embodying techno-social orders",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/16/26 – 2/5/27",
        "startDate": "2026-10-16",
        "endDate": "2027-02-05",
        "note": null
      }
    ],
    "location": "AR-K 116",
    "lecturers": [
      "Univ.-Prof. Dr. Jörg Potthast"
    ],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "cultural-sociology",
      "label": "Cultural Sociology",
      "ects": 3
    }
  },
  {
    "id": "1mewi3826v-ws26-27",
    "code": "1MEWI3826V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA08",
        "name": "Science, Technology and Media Studies"
      }
    ],
    "name": "Environmental Communication",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": "AH-A 110",
    "lecturers": [
      "Prof. Dr. Mine Gencel Bek"
    ],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "science-technology-media",
      "label": "Science, Technology and Media Studies",
      "ects": 3
    }
  },
  {
    "id": "1mewi3830v-ws26-27",
    "code": "1MEWI3830V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA09",
        "name": "Digital Anthropology"
      }
    ],
    "name": "Ethnographies of AI",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "14:00",
        "endTime": "18:00",
        "cadence": "fortnightly",
        "dateLabel": "10/21/26 – 2/3/27",
        "startDate": "2026-10-21",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "AH-A 031/034",
    "lecturers": [
      "Univ.-Prof. Dr. Götz Bachmann"
    ],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "digital-anthropology",
      "label": "Digital Anthropology",
      "ects": 3
    }
  },
  {
    "id": "1mewi3832v-ws26-27",
    "code": "1MEWI3832V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA03",
        "name": "Media History and Media Historiography"
      }
    ],
    "name": "Fandom zwischen Praktiken und gesellschaftlichem Diskurs",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "AH-A 036/039",
    "lecturers": [],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "media-history",
      "label": "Media History and Media Historiography",
      "ects": 3
    }
  },
  {
    "id": "1mewi3829v-ws26-27",
    "code": "1MEWI3829V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA02",
        "name": "Media Aesthetics"
      }
    ],
    "name": "Filme in vier Wänden. Ästhetik und Dramaturgie geschlossener Räume",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/16/26 – 2/5/27",
        "startDate": "2026-10-16",
        "endDate": "2027-02-05",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Dr. Martin Siegler"
    ],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "media-aesthetics",
      "label": "Media Aesthetics",
      "ects": 3
    }
  },
  {
    "id": "1mewi3835v-ws26-27",
    "code": "1MEWI3835V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA02",
        "name": "Media Aesthetics"
      }
    ],
    "name": "Fotografie im Film",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "AH-A 110",
    "lecturers": [
      "PD Dr. Sandra Nuy"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "media-aesthetics",
      "label": "Media Aesthetics",
      "ects": 3
    }
  },
  {
    "id": "1mewi3837v-ws26-27",
    "code": "1MEWI3837V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA01",
        "name": "Media and Cultural Theory"
      }
    ],
    "name": "Foucault 100",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "AH-A 110",
    "lecturers": [
      "PD Dr. Sebastian Gießmann"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "media-cultural-theory",
      "label": "Media and Cultural Theory",
      "ects": 3
    }
  },
  {
    "id": "1mewi3838v-ws26-27",
    "code": "1MEWI3838V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA07",
        "name": "Data, Platforms and Digital Methods"
      }
    ],
    "name": "From Media to Data. Critical Perspectives on Data Practices in Digital Cultures",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "AH-A 125",
    "lecturers": [
      "Dr. Christoph Borbach"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "data-platforms",
      "label": "Data, Platforms and Digital Methods",
      "ects": 3
    }
  },
  {
    "id": "3moog0021v-ws26-27",
    "code": "3MOOG0021V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3SMEMA015",
        "name": "Nuts and Bolts of Business Plan"
      }
    ],
    "name": "How to write a Business Plan",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "US-A 234",
    "lecturers": [
      "Univ.-Prof. Dr. Giuseppe Strina"
    ],
    "creditGroup": {
      "id": "nuts-and-bolts",
      "label": "Nuts and Bolts of Business Plan",
      "ects": 9,
      "parts": 2
    }
  },
  {
    "id": "3nieha001v-ws26-27",
    "code": "3NIEHA001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3WIMA003",
        "name": "Operational Information Systems"
      }
    ],
    "name": "Information Management",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "US-F 103",
    "lecturers": [
      "Prof. Dr. Dirk Schreiber"
    ],
    "moduleCreditNote": "Operational Information Systems is 9 ECTS. All courses in the module have to be completed before the credits count."
  },
  {
    "id": "3nieha028v-ws26-27",
    "code": "3NIEHA028V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3WIMA003",
        "name": "Operational Information Systems"
      }
    ],
    "name": "Information Management",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "US-F 103",
    "lecturers": [
      "Prof. Dr. Dirk Schreiber"
    ]
  },
  {
    "id": "3eigle108v-ws26-27",
    "code": "3EIGLE108V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "Introduction to E-Business / Grundlagen des E-Business",
    "requirementStatus": null,
    "recommendedSemesters": [
      3
    ],
    "offeringFrequency": "Every 2nd semester",
    "ects": null,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "US-F 304",
    "lecturers": [
      "Univ.-Prof. Dr. Joachim Eigler"
    ],
    "lectureGroupFrequency": "Every semester",
    "moduleCreditNote": "New Media Management is 9 ECTS. All courses in the module have to be completed before the credits count."
  },
  {
    "id": "43uco1114v-ws26-27",
    "code": "43UCO1114V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Introduction to Programming",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "H-C 3305",
    "lecturers": [
      "Univ.-Prof. Dr. Kristof Van Laerhoven"
    ],
    "creditGroup": {
      "id": "intro-programming",
      "label": "Introduction to Programming",
      "ects": 9,
      "parts": 2
    }
  },
  {
    "id": "43uco1115v-ws26-27",
    "code": "43UCO1115V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Introduction to Programming",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "weekly",
        "dateLabel": "10/16/26 – 2/5/27",
        "startDate": "2026-10-16",
        "endDate": "2027-02-05",
        "note": null
      }
    ],
    "location": "H-C 3305",
    "lecturers": [
      "Univ.-Prof. Dr. Kristof Van Laerhoven"
    ],
    "creditGroup": {
      "id": "intro-programming",
      "label": "Introduction to Programming",
      "ects": 9,
      "parts": 2
    }
  },
  {
    "id": "1mewi3843v-ws26-27",
    "code": "1MEWI3843V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA09",
        "name": "Digital Anthropology"
      }
    ],
    "name": "Kulturen des Enthusiasmus. Medienanthropologische Positionen zum benevolenten Einfluss zwischen Politik, Religion und Kunst",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "AH-A 036/039",
    "lecturers": [
      "PD Dr. Bernd Bösel"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "digital-anthropology",
      "label": "Digital Anthropology",
      "ects": 3
    }
  },
  {
    "id": "3wulf0009v-ws26-27",
    "code": "3WULF0009V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      },
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "Künstlerisches Gestalten",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 6,
    "schedule": [
      {
        "day": null,
        "startTime": "10:00",
        "endTime": "18:00",
        "cadence": "block",
        "dateLabel": "3/1/27 – 3/2/27",
        "startDate": "2027-03-01",
        "endDate": "2027-03-02",
        "note": null
      },
      {
        "day": null,
        "startTime": "10:00",
        "endTime": "18:00",
        "cadence": "block",
        "dateLabel": "3/15/27 – 3/16/27",
        "startDate": "2027-03-15",
        "endDate": "2027-03-16",
        "note": null
      }
    ],
    "location": "US-A 016",
    "lecturers": [
      "Yue Dreier-Wang"
    ]
  },
  {
    "id": "999f00174v-ws26-27",
    "code": "999F00174V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      },
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      },
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "Language Center: English: Academic Writing - BA dissertation, MA thesis and academic paper writing (C1 Level)",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 3,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": null,
    "lecturers": []
  },
  {
    "id": "999f00173v-ws26-27",
    "code": "999F00173V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      },
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      },
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "Language Center: English: Introduction to Academic Writing (B2/C1 Level)",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 3,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": null,
    "lecturers": []
  },
  {
    "id": "1mewi3831v-ws26-27",
    "code": "1MEWI3831V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA09",
        "name": "Digital Anthropology"
      }
    ],
    "name": "Media Tech and Anthropology",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "AH-A 110",
    "lecturers": [
      "Univ.-Prof. Dr. Götz Bachmann"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "digital-anthropology",
      "label": "Digital Anthropology",
      "ects": 3
    }
  },
  {
    "id": "1mewi3825v-ws26-27",
    "code": "1MEWI3825V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA04",
        "name": "Cultural Sociology"
      }
    ],
    "name": "Media and Democracy",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": "AH-A 110",
    "lecturers": [
      "Prof. Dr. Mine Gencel Bek"
    ],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "cultural-sociology",
      "label": "Cultural Sociology",
      "ects": 3
    }
  },
  {
    "id": "1mewi3809v-ws26-27",
    "code": "1MEWI3809V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA08",
        "name": "Science, Technology and Media Studies"
      }
    ],
    "name": "Medien der Künstlichen Intelligenz",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "AH-A 110",
    "lecturers": [
      "Univ.-Prof. Dr. Tristan Thielmann"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "science-technology-media",
      "label": "Science, Technology and Media Studies",
      "ects": 3
    }
  },
  {
    "id": "1mewi3834v-ws26-27",
    "code": "1MEWI3834V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA04",
        "name": "Cultural Sociology"
      }
    ],
    "name": "Medienkulturen und Subjektivierung",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "AH-A 110",
    "lecturers": [
      "Univ.-Prof. Dr. Dagmar Hoffmann"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "cultural-sociology",
      "label": "Cultural Sociology",
      "ects": 3
    }
  },
  {
    "id": "1mewi3856v-ws26-27",
    "code": "1MEWI3856V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA07",
        "name": "Data, Platforms and Digital Methods"
      }
    ],
    "name": "Metaphoriken digitaler Kulturen",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "single",
        "dateLabel": "10/23/26",
        "startDate": "2026-10-23",
        "endDate": "2026-10-23",
        "note": null
      },
      {
        "day": "Friday",
        "startTime": "12:00",
        "endTime": "18:00",
        "cadence": "single",
        "dateLabel": "11/13/26",
        "startDate": "2026-11-13",
        "endDate": "2026-11-13",
        "note": null
      },
      {
        "day": "Friday",
        "startTime": "12:00",
        "endTime": "18:00",
        "cadence": "single",
        "dateLabel": "11/6/26",
        "startDate": "2026-11-06",
        "endDate": "2026-11-06",
        "note": null
      },
      {
        "day": "Friday",
        "startTime": "12:00",
        "endTime": "18:00",
        "cadence": "single",
        "dateLabel": "12/11/26",
        "startDate": "2026-12-11",
        "endDate": "2026-12-11",
        "note": null
      },
      {
        "day": "Friday",
        "startTime": "12:00",
        "endTime": "18:00",
        "cadence": "single",
        "dateLabel": "12/4/26",
        "startDate": "2026-12-04",
        "endDate": "2026-12-04",
        "note": null
      }
    ],
    "location": "AH-A 031/034",
    "lecturers": [
      "Dr. Christoph Borbach"
    ],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "data-platforms",
      "label": "Data, Platforms and Digital Methods",
      "ects": 3
    }
  },
  {
    "id": "1sowi1003v-ws26-27",
    "code": "1SOWI1003V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1SOWIMA03",
        "name": "Statistics"
      },
      {
        "code": "1MEWIMA10",
        "name": "Digital Explorations Lab"
      }
    ],
    "name": "Multivariate Statistik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": null,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "AR-D 6103",
    "lecturers": [
      "Univ.-Prof. Dr. Matthias Pollmann-Schult"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true,
    "creditGroup": {
      "id": "statistics",
      "label": "Statistics",
      "ects": 9,
      "parts": 2
    }
  },
  {
    "id": "43cgm1116v-ws26-27",
    "code": "43CGM1116V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      }
    ],
    "name": "Practical Course 3D- modeling and animation Practical Training \"3D Modeling and Animation\"",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 6,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "H-A 4111",
    "lecturers": [
      "Dipl.-Inform. Ulrich Schipper"
    ]
  },
  {
    "id": "43cgm1129v-ws26-27",
    "code": "43CGM1129V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      }
    ],
    "name": "Practical Course Computergraphics Computer Graphics Lab",
    "requirementStatus": null,
    "recommendedSemesters": [
      1
    ],
    "offeringFrequency": "Winter semester only",
    "ects": 6,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "H-C 7326",
    "lecturers": [
      "Dr. Marina Evers"
    ]
  },
  {
    "id": "3ludwi033v-ws26-27",
    "code": "3LUDWI033V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3WIMA003",
        "name": "Operational Information Systems"
      }
    ],
    "name": "Process Management",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": "US-F 103",
    "lecturers": [
      "Univ.-Prof. Dr. Thomas Ludwig"
    ]
  },
  {
    "id": "3ludwi034v-ws26-27",
    "code": "3LUDWI034V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3WIMA003",
        "name": "Operational Information Systems"
      }
    ],
    "name": "Process Management",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "even weeks",
        "dateLabel": "10/15/26 – 1/28/27",
        "startDate": "2026-10-15",
        "endDate": "2027-01-28",
        "note": null
      }
    ],
    "location": "US-F 103",
    "lecturers": [
      "Univ.-Prof. Dr. Thomas Ludwig"
    ]
  },
  {
    "id": "1mewi3858v-ws26-27",
    "code": "1MEWI3858V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA01",
        "name": "Media and Cultural Theory"
      }
    ],
    "name": "Queer Theory & Media Representations of Queerness",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "AH-A 036/039",
    "lecturers": [],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "media-cultural-theory",
      "label": "Media and Cultural Theory",
      "ects": 3
    }
  },
  {
    "id": "1mewi3840v-ws26-27",
    "code": "1MEWI3840V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA10",
        "name": "Digital Explorations Lab"
      }
    ],
    "name": "Research Approaches to Synthetic Social Media",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "AH-A 036/039",
    "lecturers": [
      "Dr. Elena Pilipets"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "digital-explorations",
      "label": "Digital Explorations Lab",
      "ects": 3
    }
  },
  {
    "id": "1sowi1002v-ws26-27",
    "code": "1SOWI1002V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1SOWIMA03",
        "name": "Statistics"
      },
      {
        "code": "1MEWIMA10",
        "name": "Digital Explorations Lab"
      }
    ],
    "name": "Schließende Statistik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": null,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "AR-HB 123",
    "lecturers": [
      "Univ.-Prof. Dr. Matthias Pollmann-Schult"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true,
    "creditGroup": {
      "id": "statistics",
      "label": "Statistics",
      "ects": 9,
      "parts": 2
    }
  },
  {
    "id": "43eti0001v-concepts-of-programming-languages-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "13:00",
        "endTime": "14:00",
        "cadence": "single",
        "dateLabel": "10/20/26",
        "startDate": "2026-10-20",
        "endDate": "2026-10-20",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Felix Breitweiser",
      "Univ.-Prof. Dr. rer. nat. Roland Wismüller"
    ],
    "variant": "Concepts of Programming Languages"
  },
  {
    "id": "43eti0001v-embedded-systems-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "09:30",
        "endTime": "11:30",
        "cadence": "single",
        "dateLabel": "10/16/26",
        "startDate": "2026-10-16",
        "endDate": "2026-10-16",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Embedded Systems"
  },
  {
    "id": "43eti0001v-data-science-machine-learning-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "09:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "10/20/26",
        "startDate": "2026-10-20",
        "endDate": "2026-10-20",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "1/26/27",
        "startDate": "2027-01-26",
        "endDate": "2027-01-26",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "2/2/27",
        "startDate": "2027-02-02",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Data Science - Machine Learning"
  },
  {
    "id": "43eti0001v-theoretical-computer-science-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "single",
        "dateLabel": "10/19/26",
        "startDate": "2026-10-19",
        "endDate": "2026-10-19",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Theoretical Computer Science"
  },
  {
    "id": "43eti0001v-computer-vision-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "single",
        "dateLabel": "10/21/26",
        "startDate": "2026-10-21",
        "endDate": "2026-10-21",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Computer Vision"
  },
  {
    "id": "43eti0001v-intelligent-systems-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "16:15",
        "endTime": "17:45",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      },
      {
        "day": "Friday",
        "startTime": "08:15",
        "endTime": "09:45",
        "cadence": "weekly",
        "dateLabel": "10/16/26 – 2/5/27",
        "startDate": "2026-10-16",
        "endDate": "2027-02-05",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Intelligent Systems"
  },
  {
    "id": "43eti0001v-reliable-and-trustworthy-ai-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Reliable and Trustworthy AI"
  },
  {
    "id": "43eti0001v-applications-in-ml-generative-ai-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "10:00",
        "endTime": "13:00",
        "cadence": "single",
        "dateLabel": "11/5/26",
        "startDate": "2026-11-05",
        "endDate": "2026-11-05",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Applications in ML: Developing Generative AI Systems"
  },
  {
    "id": "43eti0001v-applications-in-ml-agentic-coding-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "10:00",
        "endTime": "13:00",
        "cadence": "single",
        "dateLabel": "11/10/26",
        "startDate": "2026-11-10",
        "endDate": "2026-11-10",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Applications in ML: Agentic Coding"
  },
  {
    "id": "43eti0001v-visual-computing-foundation-models-ws26-27",
    "code": "43ETI0001V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      }
    ],
    "name": "Seminar Informatik",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 9,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "13:00",
        "endTime": "14:00",
        "cadence": "single",
        "dateLabel": "10/21/26",
        "startDate": "2026-10-21",
        "endDate": "2026-10-21",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "variant": "Visual Computing: Scaling in the Context of Foundation Models"
  },
  {
    "id": "999f5aa98v-ws26-27",
    "code": "999F5AA98V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      },
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "SiegMUN (Model United Nations Siegen) Preparatory and Companion Seminar",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Saturday",
        "startTime": "10:00",
        "endTime": "14:30",
        "cadence": "single",
        "dateLabel": "11/7/26",
        "startDate": "2026-11-07",
        "endDate": "2026-11-07",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "18:00",
        "endTime": "19:00",
        "cadence": "single",
        "dateLabel": "10/20/26",
        "startDate": "2026-10-20",
        "endDate": "2026-10-20",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "18:00",
        "endTime": "20:00",
        "cadence": "single",
        "dateLabel": "10/27/26",
        "startDate": "2026-10-27",
        "endDate": "2026-10-27",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "18:00",
        "endTime": "20:00",
        "cadence": "single",
        "dateLabel": "11/10/26",
        "startDate": "2026-11-10",
        "endDate": "2026-11-10",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "18:00",
        "endTime": "20:00",
        "cadence": "single",
        "dateLabel": "11/17/26",
        "startDate": "2026-11-17",
        "endDate": "2026-11-17",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "18:00",
        "endTime": "20:00",
        "cadence": "single",
        "dateLabel": "11/3/26",
        "startDate": "2026-11-03",
        "endDate": "2026-11-03",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "18:00",
        "endTime": "19:00",
        "cadence": "single",
        "dateLabel": "12/1/26",
        "startDate": "2026-12-01",
        "endDate": "2026-12-01",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  },
  {
    "id": "999f00165v-ws26-27",
    "code": "999F00165V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA013",
        "name": "Interdisciplinary Contexts in HCI Ia (9 LP)"
      },
      {
        "code": "3HCIMA014",
        "name": "Interdisciplinary Contexts in HCI IIa (9 LP)"
      },
      {
        "code": "3HCIMA022",
        "name": "Interdisciplinary Contexts in HCI IIIa (9 LP)"
      },
      {
        "code": "3HCIMA023",
        "name": "Interdisciplinary Contexts in HCI IVa (9 LP)"
      },
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      },
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "Sprachenzentrum: Englisch - Zielstufe C1.1",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 3,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "single",
        "dateLabel": "12/18/26",
        "startDate": "2026-12-18",
        "endDate": "2026-12-18",
        "note": null
      },
      {
        "day": "Thursday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "single",
        "dateLabel": "12/17/26",
        "startDate": "2026-12-17",
        "endDate": "2026-12-17",
        "note": null
      },
      {
        "day": "Wednesday",
        "startTime": "10:30",
        "endTime": "13:30",
        "cadence": "single",
        "dateLabel": "1/13/27",
        "startDate": "2027-01-13",
        "endDate": "2027-01-13",
        "note": null,
        "location": "F-S 0101"
      },
      {
        "day": "Wednesday",
        "startTime": "10:30",
        "endTime": "13:30",
        "cadence": "single",
        "dateLabel": "1/20/27",
        "startDate": "2027-01-20",
        "endDate": "2027-01-20",
        "note": null,
        "location": "F-S 0101"
      },
      {
        "day": "Tuesday",
        "startTime": "14:00",
        "endTime": "16:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null,
        "location": "F-S 011"
      }
    ],
    "location": null,
    "lecturers": []
  },
  {
    "id": "3moog0023v-ws26-27",
    "code": "3MOOG0023V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3SMEMA015",
        "name": "Nuts and Bolts of Business Plan"
      }
    ],
    "name": "Start-up of new SMEs",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Winter semester only",
    "ects": null,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "weekly",
        "dateLabel": "10/15/26 – 2/4/27",
        "startDate": "2026-10-15",
        "endDate": "2027-02-04",
        "note": null
      }
    ],
    "location": "US-A 234",
    "lecturers": [
      "Univ.-Prof. Dr. Giuseppe Strina"
    ],
    "creditGroup": {
      "id": "nuts-and-bolts",
      "label": "Nuts and Bolts of Business Plan",
      "ects": 9,
      "parts": 2
    }
  },
  {
    "id": "1mewi3853v-ws26-27",
    "code": "1MEWI3853V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA10",
        "name": "Digital Explorations Lab"
      }
    ],
    "name": "Synthetic Toolmaking",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": "AH-A 125",
    "lecturers": [
      "Sergei Pashakhin"
    ],
    "lectureGroupFrequency": "Winter semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "digital-explorations",
      "label": "Digital Explorations Lab",
      "ects": 3
    }
  },
  {
    "id": "43uco1113v-ws26-27",
    "code": "43UCO1113V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA015",
        "name": "Interdisciplinary Contexts in HCI Ib (6 LP)"
      },
      {
        "code": "3HCIMA019",
        "name": "Interdisciplinary Contexts in HCI IIb (6 LP)"
      },
      {
        "code": "3HCIMA020",
        "name": "Interdisciplinary Contexts in HCI IIIb (6 LP)"
      },
      {
        "code": "3HCIMA024",
        "name": "Interdisciplinary Contexts in HCI IVb (6 LP)"
      }
    ],
    "name": "Ubiquitous Systems Lab",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": "Every semester",
    "ects": 6,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": "H-C 7326",
    "lecturers": [
      "Univ.-Prof. Dr. Kristof Van Laerhoven"
    ]
  },
  {
    "id": "1mewi3842v-ws26-27",
    "code": "1MEWI3842V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "1MEWIMA01",
        "name": "Media and Cultural Theory"
      }
    ],
    "name": "Warum es die Technik nicht gibt – Eine Einführung in alternative Konzeptionen des Technischen",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      3
    ],
    "offeringFrequency": null,
    "ects": 3,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": "AH-A 031/034",
    "lecturers": [
      "PD Dr. Bernd Bösel"
    ],
    "lectureGroupFrequency": "Summer semester only",
    "irregularOffering": true,
    "examCredit": {
      "groupId": "media-cultural-theory",
      "label": "Media and Cultural Theory",
      "ects": 3
    }
  },
  {
    "id": "3eigle109v-ws26-27",
    "code": "3EIGLE109V",
    "semesterId": "WS26-27",
    "area": "Interdisciplinary Contexts",
    "modules": [
      {
        "code": "3HCIMA025",
        "name": "Interdisciplinary Contexts in HCI Vb (6 LP)"
      }
    ],
    "name": "Übung zu Introduction to E-Business / Grundlagen des E-Business",
    "requirementStatus": null,
    "recommendedSemesters": [
      3
    ],
    "offeringFrequency": "Every 2nd semester",
    "ects": null,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "11/10/26",
        "startDate": "2026-11-10",
        "endDate": "2026-11-10",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "11/24/26",
        "startDate": "2026-11-24",
        "endDate": "2026-11-24",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "12/8/26",
        "startDate": "2026-12-08",
        "endDate": "2026-12-08",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "12/22/26",
        "startDate": "2026-12-22",
        "endDate": "2026-12-22",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "1/12/27",
        "startDate": "2027-01-12",
        "endDate": "2027-01-12",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "single",
        "dateLabel": "1/26/27",
        "startDate": "2027-01-26",
        "endDate": "2027-01-26",
        "note": null
      }
    ],
    "location": "US-F 304",
    "lecturers": [
      "Jessica Knodel M.A."
    ],
    "lectureGroupFrequency": "Every semester",
    "datedGrid": true,
    "moduleCreditNote": "New Media Management is 9 ECTS. All courses in the module have to be completed before the credits count."
  },
  {
    "id": "3wulf0056v-ws26-27",
    "code": "3WULF0056V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA004",
        "name": "Project A"
      },
      {
        "code": "3HCIMA005",
        "name": "Project B"
      },
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "AI-Enabled Individual Identification of Wild Animals",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Friday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "single",
        "dateLabel": "10/16/26",
        "startDate": "2026-10-16",
        "endDate": "2026-10-16",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Dr. Felix Bernhard Carros"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  },
  {
    "id": "3muecl015v-ws26-27",
    "code": "3MUECL015V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA004",
        "name": "Project A"
      },
      {
        "code": "3HCIMA005",
        "name": "Project B"
      },
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "Accessibility and workplaces",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "single",
        "dateLabel": "10/15/26",
        "startDate": "2026-10-15",
        "endDate": "2026-10-15",
        "note": null
      }
    ],
    "location": "US-F 002",
    "lecturers": [
      "Dipl.-Wirt.-Inform. Sven Bittenbinder"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  },
  {
    "id": "3muecl031v-ws26-27",
    "code": "3MUECL031V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA004",
        "name": "Project A"
      },
      {
        "code": "3HCIMA005",
        "name": "Project B"
      },
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "Community Care and cooperative media: Telemedicine and Telecare in Germany and Japan",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Thursday",
        "startTime": "10:00",
        "endTime": "12:00",
        "cadence": "single",
        "dateLabel": "10/15/26",
        "startDate": "2026-10-15",
        "endDate": "2026-10-15",
        "note": null
      }
    ],
    "location": "US-A 134",
    "lecturers": [
      "Dennis Kirschsieper"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  },
  {
    "id": "3muecl036v-ws26-27",
    "code": "3MUECL036V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA004",
        "name": "Project A"
      },
      {
        "code": "3HCIMA005",
        "name": "Project B"
      },
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "From Ideation to Prototyping: Exploring Design Spaces for BCI-Enhanced Everyday Interactions",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "16:00",
        "endTime": "18:00",
        "cadence": "fortnightly",
        "dateLabel": "10/13/26 – 2/2/27",
        "startDate": "2026-10-13",
        "endDate": "2027-02-02",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Sourav Bhattacharjee"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  },
  {
    "id": "3muecl045v-ws26-27",
    "code": "3MUECL045V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA004",
        "name": "Project A"
      },
      {
        "code": "3HCIMA005",
        "name": "Project B"
      },
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "From Lifelong Learning to Late-Life Working: Digitalisation and the Ageing Workforce",
    "requirementStatus": null,
    "recommendedSemesters": [
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "single",
        "dateLabel": "10/12/26",
        "startDate": "2026-10-12",
        "endDate": "2026-10-12",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Kyra Malinda Dunkel"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  },
  {
    "id": "3wulf0057v-ws26-27",
    "code": "3WULF0057V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA004",
        "name": "Project A"
      },
      {
        "code": "3HCIMA005",
        "name": "Project B"
      },
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "Grassroots Digital Infrastructures: Censorship, Circumvention, and Design for Internet Freedom",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "08:00",
        "endTime": "10:00",
        "cadence": "weekly",
        "dateLabel": "10/12/26 – 2/1/27",
        "startDate": "2026-10-12",
        "endDate": "2027-02-01",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Parvin Ghadamighalandari"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  },
  {
    "id": "3sadeg104v-ws26-27",
    "code": "3SADEG104V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "Making Automated Systems 2",
    "requirementStatus": "Core elective",
    "recommendedSemesters": [
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Tuesday",
        "startTime": "16:00",
        "endTime": "17:00",
        "cadence": "single",
        "dateLabel": "10/13/26",
        "startDate": "2026-10-13",
        "endDate": "2026-10-13",
        "note": null
      },
      {
        "day": "Tuesday",
        "startTime": "16:00",
        "endTime": "17:00",
        "cadence": "single",
        "dateLabel": "10/20/26",
        "startDate": "2026-10-20",
        "endDate": "2026-10-20",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Jun.-Prof. Dr.-Ing. Shadan Sadeghian Borojeni"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true,
    "datedGrid": true
  },
  {
    "id": "3muecl046v-ws26-27",
    "code": "3MUECL046V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA004",
        "name": "Project A"
      },
      {
        "code": "3HCIMA005",
        "name": "Project B"
      },
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "Seeking the Spark: Understanding what motivates older adults to learn and make digitally",
    "requirementStatus": null,
    "recommendedSemesters": [
      1,
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Monday",
        "startTime": "12:00",
        "endTime": "14:00",
        "cadence": "single",
        "dateLabel": "10/12/26",
        "startDate": "2026-10-12",
        "endDate": "2026-10-12",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Kyra Malinda Dunkel"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  },
  {
    "id": "3hasse020v-ws26-27",
    "code": "3HASSE020V",
    "semesterId": "WS26-27",
    "area": "Practice",
    "modules": [
      {
        "code": "3HCIMA004",
        "name": "Project A"
      },
      {
        "code": "3HCIMA005",
        "name": "Project B"
      },
      {
        "code": "3HCIMA006",
        "name": "Project C"
      }
    ],
    "name": "The Patient as User? – Rethinking Autonomy in Healthcare Interactions",
    "requirementStatus": null,
    "recommendedSemesters": [
      2,
      3
    ],
    "offeringFrequency": null,
    "ects": 9,
    "schedule": [
      {
        "day": "Wednesday",
        "startTime": "09:00",
        "endTime": "12:00",
        "cadence": "weekly",
        "dateLabel": "10/14/26 – 2/3/27",
        "startDate": "2026-10-14",
        "endDate": "2027-02-03",
        "note": null
      }
    ],
    "location": null,
    "lecturers": [
      "Christian Joachim Spengler M.Sc.",
      "Univ.-Prof. Dr. Marc Hassenzahl"
    ],
    "lectureGroupFrequency": "Every semester",
    "irregularOffering": true
  }
] satisfies Course[];
