// Generated by scripts/build_interdisciplinary_catalog.py.
// 9 LP follows Ia, then New Media Management and Media Law.
// 6 LP is the deduped Ib list. Vb omits the courses flagged notInVb.

export type CatalogEntry = { courseId: string } | { title: string };

export type CatalogGroup = {
  name: string;
  entries: CatalogEntry[];
};

export type CatalogSection = {
  name: string;
  groups: CatalogGroup[];
};

export type Lp6Course = {
  courseId: string;
  notInVb?: true;
};

export const TRACK_RULE =
  "Choose two 9 LP modules or three 6 LP modules.";

export const LP9_NOTE = "Semester 1: Ia or IIa. Courses for semester 3 are not shown.";

export const LP6_NOTE = "Semester 1: Ib or IIb. Courses for semester 3 are not shown.";

const catalog = {
  "lp9": [
    {
      "name": "Offered in Ia–IVa",
      "groups": [
        {
          "name": "",
          "entries": [
            {
              "courseId": "43ems0030v-ws26-27"
            },
            {
              "courseId": "43uco1114v-ws26-27"
            },
            {
              "courseId": "999f00173v-ws26-27"
            },
            {
              "courseId": "999f00174v-ws26-27"
            },
            {
              "courseId": "999f00167v-ws26-27"
            },
            {
              "courseId": "999f00165v-ws26-27"
            },
            {
              "courseId": "43uco1115v-ws26-27"
            },
            {
              "courseId": "43ems0031v-ws26-27"
            },
            {
              "courseId": "43eti0001v-concepts-of-programming-languages-ws26-27"
            },
            {
              "courseId": "43eti0001v-embedded-systems-ws26-27"
            },
            {
              "title": "Seminar Informatik (Model-based Engineering)"
            },
            {
              "courseId": "43eti0001v-data-science-machine-learning-ws26-27"
            },
            {
              "courseId": "43eti0001v-theoretical-computer-science-ws26-27"
            },
            {
              "courseId": "43eti0001v-computer-vision-ws26-27"
            },
            {
              "courseId": "43eti0001v-intelligent-systems-ws26-27"
            },
            {
              "courseId": "43eti0001v-reliable-and-trustworthy-ai-ws26-27"
            },
            {
              "title": "Seminar Informatik (Media Infomatics)"
            },
            {
              "courseId": "43eti0001v-applications-in-ml-generative-ai-ws26-27"
            },
            {
              "courseId": "43eti0001v-applications-in-ml-agentic-coding-ws26-27"
            },
            {
              "courseId": "43eti0001v-visual-computing-foundation-models-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Decision Support",
      "groups": [
        {
          "name": "Decision Support Systems (Lecture & Exercise)",
          "entries": [
            {
              "courseId": "3pesch101v-ws26-27"
            }
          ]
        },
        {
          "name": "Scheduling",
          "entries": []
        },
        {
          "name": "Decision Support",
          "entries": []
        }
      ]
    },
    {
      "name": "Operational Information Systems",
      "groups": [
        {
          "name": "Information Management",
          "entries": [
            {
              "courseId": "3nieha001v-ws26-27"
            },
            {
              "courseId": "3nieha028v-ws26-27"
            }
          ]
        },
        {
          "name": "Process Management",
          "entries": [
            {
              "courseId": "3ludwi033v-ws26-27"
            },
            {
              "courseId": "3ludwi034v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Nuts and Bolts of Business Plan",
      "groups": [
        {
          "name": "Start-up of new SMEs",
          "entries": [
            {
              "courseId": "3moog0023v-ws26-27"
            }
          ]
        },
        {
          "name": "How to write a Business Plan",
          "entries": [
            {
              "courseId": "3moog0021v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Strategic and Life Cycle Management in SMEs",
      "groups": [
        {
          "name": "Strategic and International Management in SME",
          "entries": []
        },
        {
          "name": "Life Cycle Management",
          "entries": []
        }
      ]
    },
    {
      "name": "Development and Distribution",
      "groups": [
        {
          "name": "Introduction to Economic Growth",
          "entries": []
        },
        {
          "name": "Case Study Seminar",
          "entries": []
        }
      ]
    },
    {
      "name": "Economic Journalism",
      "groups": [
        {
          "name": "Economics and Business Journalism (Lecture)",
          "entries": []
        },
        {
          "name": "Seminar on Business Journalism (Seminar)",
          "entries": []
        }
      ]
    },
    {
      "name": "Organizational Development and Systems",
      "groups": [
        {
          "name": "Systematic Organizational Development and Coaching (Lecture (with case study discussion and exercise))",
          "entries": []
        },
        {
          "name": "Empirical Projects in Organizational Development (Seminar [with case studies and exercise])",
          "entries": []
        }
      ]
    },
    {
      "name": "Media and Cultural Theory",
      "groups": [
        {
          "name": "History of Media and Culture Theory",
          "entries": [
            {
              "courseId": "1mewi3837v-ws26-27"
            }
          ]
        },
        {
          "name": "01.2 Current Media Theories",
          "entries": [
            {
              "courseId": "1mewi3842v-ws26-27"
            },
            {
              "courseId": "1mewi3858v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Media Aesthetics",
      "groups": [
        {
          "name": "02.1 Time-Based Media",
          "entries": [
            {
              "courseId": "1mewi3835v-ws26-27"
            }
          ]
        },
        {
          "name": "02.2 Space-Based Media",
          "entries": [
            {
              "courseId": "1mewi3829v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Media History and Media Historiography",
      "groups": [
        {
          "name": "03.1 Media History and Media Historiography",
          "entries": [
            {
              "courseId": "1mewi3828v-ws26-27"
            }
          ]
        },
        {
          "name": "03.2 Digital History of Media",
          "entries": [
            {
              "courseId": "1mewi3832v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Cultural Sociology",
      "groups": [
        {
          "name": "04.1 Subject, Media Culture, and Society",
          "entries": [
            {
              "courseId": "1mewi3834v-ws26-27"
            }
          ]
        },
        {
          "name": "04.2 Research Access to Cultural Sociology",
          "entries": [
            {
              "courseId": "1sowi1404v-ws26-27"
            },
            {
              "courseId": "1mewi3825v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Data, Platforms and Digital Methods",
      "groups": [
        {
          "name": "07.1 Data Critique and Digital Infrastructures",
          "entries": [
            {
              "courseId": "1mewi3838v-ws26-27"
            }
          ]
        },
        {
          "name": "07.2 Digital Methods",
          "entries": [
            {
              "courseId": "1mewi3856v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Science, Technology and Media Studies",
      "groups": [
        {
          "name": "08.1 Innovations: Foundations of Science, Technology and Media Studies",
          "entries": [
            {
              "courseId": "1mewi3809v-ws26-27"
            }
          ]
        },
        {
          "name": "08.2 Interventions: Research Fields of Science, Technology and Media Studies",
          "entries": [
            {
              "courseId": "1sowi1406v-ws26-27"
            },
            {
              "courseId": "1mewi3826v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Digital Anthropology",
      "groups": [
        {
          "name": "09.1 Media Anthropology",
          "entries": [
            {
              "courseId": "1mewi3831v-ws26-27"
            },
            {
              "courseId": "1mewi3843v-ws26-27"
            }
          ]
        },
        {
          "name": "09.2 Digital Ethnography",
          "entries": [
            {
              "courseId": "1mewi3830v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Digital Explorations Lab",
      "groups": [
        {
          "name": "10.1 Current Issues",
          "entries": [
            {
              "courseId": "1mewi3853v-ws26-27"
            }
          ]
        },
        {
          "name": "10.2 Research Approaches",
          "entries": [
            {
              "courseId": "1mewi3840v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "Statistics",
      "groups": [
        {
          "name": "03.1 Inferential Statistics",
          "entries": [
            {
              "courseId": "1sowi1002v-ws26-27"
            }
          ]
        },
        {
          "name": "03.2 Multivariate Statistics",
          "entries": [
            {
              "courseId": "1sowi1003v-ws26-27"
            }
          ]
        }
      ]
    },
    {
      "name": "New Media Management",
      "groups": [
        {
          "name": "Introduction to E-Business",
          "entries": [
            {
              "courseId": "3eigle108v-ws26-27"
            },
            {
              "courseId": "3eigle109v-ws26-27"
            }
          ]
        },
        {
          "name": "Electronic Commerce",
          "entries": []
        }
      ]
    },
    {
      "name": "Media Law",
      "groups": [
        {
          "name": "Constitutional Media Law",
          "entries": []
        },
        {
          "name": "Law of News Coverage, Word and Picture",
          "entries": []
        }
      ]
    }
  ],
  "lp6": [
    {
      "courseId": "999f00173v-ws26-27"
    },
    {
      "courseId": "43vsa0131v-ws26-27",
      "notInVb": true
    },
    {
      "courseId": "999f00167v-ws26-27"
    },
    {
      "courseId": "999k25005v-ws26-27"
    },
    {
      "courseId": "999f00174v-ws26-27"
    },
    {
      "courseId": "999f00165v-ws26-27"
    },
    {
      "courseId": "999f5aa98v-ws26-27"
    },
    {
      "courseId": "43vsa0132v-ws26-27",
      "notInVb": true
    },
    {
      "courseId": "3wulf0009v-ws26-27"
    },
    {
      "courseId": "43cgm1129v-ws26-27",
      "notInVb": true
    },
    {
      "courseId": "43uco1113v-ws26-27",
      "notInVb": true
    },
    {
      "courseId": "43cgm1116v-ws26-27",
      "notInVb": true
    }
  ]
} as const;

export const lp9Sections: CatalogSection[] = catalog.lp9.map((section) => ({
  name: section.name,
  groups: section.groups.map((group) => ({
    name: group.name,
    entries: group.entries.map((entry) =>
      "courseId" in entry ? { courseId: entry.courseId } : { title: entry.title },
    ),
  })),
}));

export const lp6Courses: Lp6Course[] = catalog.lp6.map((course) =>
  "notInVb" in course ? { courseId: course.courseId, notInVb: true } : { courseId: course.courseId },
);

export function lp9Placement(courseId: string): { section: string; group: string } | null {
  for (const section of lp9Sections) {
    for (const group of section.groups) {
      if (group.entries.some((entry) => "courseId" in entry && entry.courseId === courseId)) {
        return { section: section.name, group: group.name };
      }
    }
  }
  return null;
}

export function lp6Course(courseId: string): Lp6Course | null {
  return lp6Courses.find((course) => course.courseId === courseId) ?? null;
}
